# Generated by Django 5.0.6 on 2024-07-15 15:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUsersInRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(choices=[('Serikawa Lab', '芹川研究室'), ('Yamawaki Lab', '山脇研究室'), ('Yang Lab', '楊研究室'), ('Zhang Lab', '張研究室')], max_length=100, verbose_name='研究室')),
                ('entry_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'current_users_in_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyOccupancySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_time', models.DurationField()),
            ],
            options={
                'db_table': 'daily_occupancy_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostUsedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(choices=[('Serikawa Lab', '芹川研究室'), ('Yamawaki Lab', '山脇研究室'), ('Yang Lab', '楊研究室'), ('Zhang Lab', '張研究室')], max_length=100, verbose_name='研究室')),
                ('total_time', models.DurationField()),
            ],
            options={
                'db_table': 'most_used_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomUtilizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(choices=[('Serikawa Lab', '芹川研究室'), ('Yamawaki Lab', '山脇研究室'), ('Yang Lab', '楊研究室'), ('Zhang Lab', '張研究室')], max_length=100, verbose_name='研究室')),
                ('total_time', models.DurationField()),
            ],
            options={
                'db_table': 'room_utilization_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('text', models.CharField(max_length=200, verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='名前')),
                ('student_id', models.CharField(max_length=100, verbose_name='学籍番号')),
                ('grade', models.CharField(blank=True, choices=[('B4', 'B4'), ('M1', 'M1'), ('M2', 'M2')], max_length=2, null=True, verbose_name='学年')),
                ('lab', models.CharField(blank=True, choices=[('Serikawa Lab', '芹川研究室'), ('Yamawaki Lab', '山脇研究室'), ('Yang Lab', '楊研究室'), ('Zhang Lab', '張研究室')], max_length=100, null=True, verbose_name='研究室')),
                ('state', models.IntegerField(choices=[(1, 'ENTRY'), (2, 'EXIT')], verbose_name='状態')),
            ],
        ),
        migrations.CreateModel(
            name='RoomOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(choices=[('Serikawa Lab', '芹川研究室'), ('Yamawaki Lab', '山脇研究室'), ('Yang Lab', '楊研究室'), ('Zhang Lab', '張研究室')], max_length=100, verbose_name='研究室')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
