# Generated by Django 5.0.6 on 2024-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('grade', models.CharField(max_length=10)),
                ('lab', models.CharField(max_length=100)),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.RemoveField(
            model_name='roomoccupancy',
            name='person',
        ),
        migrations.DeleteModel(
            name='CurrentUsersInRoom',
        ),
        migrations.DeleteModel(
            name='DailyOccupancySummary',
        ),
        migrations.DeleteModel(
            name='MostUsedRoom',
        ),
        migrations.DeleteModel(
            name='RoomUtilizationReport',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='RoomOccupancy',
        ),
    ]
